name: mobile_app_factory
publish_to: none

environment:
  sdk: ^3.7.0

workspace:
  - packages/app_core
  - packages/ui_kit
  - packages/storage
  - packages/timer_engine
  - apps/pomodoro_app
  - apps/fasting_app

dev_dependencies:
  melos: ^7.4.0
  flutter_lints: ^6.0.0

melos:
  scripts:
    analyze:
      exec: flutter analyze
    format:
      exec: dart format .
    test:
      exec: flutter test
      packageFilters:
        flutter: true
        dirExists: test
